/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CustomeTable: typeof import('./components/CustomeTable.vue')['default']
    Filters: typeof import('./components/Filters.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedItems: typeof import('./components/SelectedItems.vue')['default']
    SeteliteTable: typeof import('./components/SeteliteTable.vue')['default']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
  }
}
